/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'medicalDevices' : IDL.Null,
  'healthSupplements' : IDL.Null,
  'babyCare' : IDL.Null,
  'otcMedicines' : IDL.Null,
  'prescriptionMedicines' : IDL.Null,
  'personalCare' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderStatus = IDL.Variant({
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'productId' : IDL.Nat,
  'productName' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Float64,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'createdAt' : IDL.Int,
  'totalAmount' : IDL.Float64,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'featured' : IDL.Bool,
  'inStock' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : Category,
  'price' : IDL.Float64,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func(
      [IDL.Text, Category, IDL.Text, IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getProductsByCategory' : IDL.Func([Category], [IDL.Vec(Product)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(OrderItem), IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchProductsByName' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'seedSampleProducts' : IDL.Func([], [], []),
  'toggleFeaturedStatus' : IDL.Func([IDL.Nat], [], []),
  'toggleStockStatus' : IDL.Func([IDL.Nat], [], []),
  'updateProduct' : IDL.Func(
      [IDL.Nat, IDL.Text, Category, IDL.Text, IDL.Float64],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'medicalDevices' : IDL.Null,
    'healthSupplements' : IDL.Null,
    'babyCare' : IDL.Null,
    'otcMedicines' : IDL.Null,
    'prescriptionMedicines' : IDL.Null,
    'personalCare' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderStatus = IDL.Variant({
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const OrderItem = IDL.Record({
    'productId' : IDL.Nat,
    'productName' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Float64,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'createdAt' : IDL.Int,
    'totalAmount' : IDL.Float64,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'featured' : IDL.Bool,
    'inStock' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : Category,
    'price' : IDL.Float64,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func(
        [IDL.Text, Category, IDL.Text, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(OrderItem), IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchProductsByName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'seedSampleProducts' : IDL.Func([], [], []),
    'toggleFeaturedStatus' : IDL.Func([IDL.Nat], [], []),
    'toggleStockStatus' : IDL.Func([IDL.Nat], [], []),
    'updateProduct' : IDL.Func(
        [IDL.Nat, IDL.Text, Category, IDL.Text, IDL.Float64],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };